#!/bin/python
"""Jean-Remy Marchand 2014
This script aims at extracting in a SDF file
generated by chemaxon only the tautomer with an
estimated occupancy > 24.9%
"""

import sys, os

if len(sys.argv)!=3:
	print "Usage = python script.py file.sdf output.sdf"

a=open(sys.argv[1], "r")
ori=a.readlines()
a.close()

out=""
tmp=""
flag=False
shouldI=False
name=""

for line in ori:
	if flag==True:
		if float(line.split()[0])>24.9:
			shouldI=True
		flag=False
		tmp+=line
	elif "tauto_occupancy" in line:
		flag=True
		tmp+=line
	else:
		tmp+=line
	if "$$$" in line:
		if shouldI==True:
			out+=tmp
			shouldI=False
		tmp=""

b=open(sys.argv[2], "w")
b.write(out)
b.close()

